# Generated by Django 4.1 on 2023-07-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_catagory_options_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
